### ISSUE TITLE
Issue: It won't start.

### ISSUE THREAD

**Issue by Sascha-T** [kukiteam/kukicraft-launcher#4]
View my comment.

**Comment by Sascha-T** [comment]
![grafik](https://user-images.githubusercontent.com/16324266/44664830-9fb04f80-aa14-11e8-89ed-53f9b68e9cef.png)

**Comment by Sascha-T** [comment]
oh
ok

**Comment by Sascha-T** [comment]
where will they be downloaded from? @NobodyMiner

**Comment by NobodyMiner** [comment]
Not sure yet ^^
Demo media file at `https://mega.nz/#!zaxHSbRK!NKwNzhG8YAVm0aiKEW9aFfb_Wu60a2kslMIJ8w_3kUg`
Just put it in `%appdata%/KukiCraft/BackgroundCache`

**Comment by Sascha-T** [comment]
I can offer https://res.sascha-t.de/kukicraft/

**Comment by Sascha-T** [comment]
![grafik](https://user-images.githubusercontent.com/16324266/44665581-84deda80-aa16-11e8-9058-8f919cd3ef40.png)
Help, the laptops dieing lmao.

We need to make it less resource using.

Btw the font is screwed up

**Comment by NobodyMiner** [comment]
#5
