### ISSUE TITLE
Whitney Font needs to be installed

### ISSUE THREAD

**Issue by NobodyMiner** [kukiteam/kukicraft-launcher#6]

**Comment by Sascha-T** [comment]
Soon:tm: Fixed

**Comment by Sascha-T** [comment]
dumb button

**Comment by NobodyMiner** [comment]
Fixed in 9cc7287c94379dca5698bdea5fbe2d8372efde2b

**Comment by Sascha-T** [comment]
Gonna find a fix now

**Comment by Sascha-T** [comment]
Damnit i was going to fix it you stuped

**Comment by Sascha-T** [comment]
I was gone for 20 minutes

**Comment by Sascha-T** [comment]
:(

**Comment by Sascha-T** [comment]
You did not fix it. You changed the font

**Comment by NobodyMiner** [comment]
We don't have a license for Whitney...
